### ISSUE TITLE
SQL Computation Caching in SQLAlchemy 1.4

### ISSUE THREAD

**Issue by SebastianSchroeder** [sqlalchemy-redshift/sqlalchemy-redshift#244]
Hello,

we are using sqlalchemy-redshift and are upgrading to SQLAlchemy 1.4. The following warning is emitted:

`SAWarning: Dialect redshift:psycopg2 will not make use of SQL compilation caching as it does not set the 'supports_statement_cache' attribute to ``True``.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Dialect maintainers should seek to set this attribute to True after appropriate development and testing for SQLAlchemy 1.4 caching support.   Alternatively, this attribute may be set to False which will disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)`

Are you planning on adding caching support? Thanks!

**Comment by Brooke-white** [comment]
Hey @SebastianSchroeder ,

Thanks for reaching out. I don't believe we have any current plans to do so, but Sqlalchemy has documented the steps we need to take before enabling support [here](https://docs.sqlalchemy.org/en/14/core/connections.html#engine-thirdparty-caching).

I took a quick look and found one incompatibility in our `RedshiftDialect_redshift_connector` [here](https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/blob/08eb50228d64a75b73aafac27c7524a9a97c3a53/sqlalchemy_redshift/dialect.py#L1022), which provides support for parameterized limit clause. This  is very much inline with the example given above in the Sqlalchemy docs.

We'd want to make a more thorough pass through and fix all issues before enabling

**Comment by ahailes** [comment]
Could the attribute be set to False until it is possibly fixed at a later date?  It's slightly noisy as is.

**Comment by Brooke-white** [comment]
Hey @ahailes -- thanks for bumping this. I'll take a look into getting this attribute set. I took a look at our CI logs and see what you mean about the noise :)

**Comment by Brooke-white** [comment]
I've opened a PR to set this flag to `False` for now to reduce the noise in our logs. I looked into enabling this feature a bit more, and think the main thing we'd need to do for that would be 
- refactoring the logic for compilation of limit/offset clauses with that provided in the sqlalchemy docs for `supports_statement_cache` flag
- writing some tests of the caching functionality (this was where I stopped as I couldn't find an example of how to do this).

**Comment by Brooke-white** [comment]
Hey @jwaterworth -- if you set `supports_statement_cache=False` do you still see this issue? We've merged a PR doing just that -- #249, but have not made a release with this change.

**Comment by Brooke-white** [comment]
@jwaterworth  -- we've made a release with this change, 0.8.10

**Comment by jwaterworth** [comment]
Hi @Brooke-white ,

Really appreciate the update, thank you!

I updated and gave it a quick go but it didn't seem to have the same effects as my test. I noticed `supports_statement_cache` is also set to true on [line 1100](https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/blob/2a7896b254bbc7d215fb992f3ef92032b054b513/sqlalchemy_redshift/dialect.py#L1100) in dialect.py. This was the line I changed in my test.

Before I found this issue I had a go at implementing the version of `limit_clause` mentioned [here](https://docs.sqlalchemy.org/en/14/core/connections.html#example-rendering-limit-offset-with-post-compile-parameters) which also seemed to fix the limit/offset caching issue and also didn't seem to require disabling statement caching. Any thoughts on this [PR](https://github.com/jwaterworth/sqlalchemy-redshift/pull/2/files) at all?

Cheers!

**Comment by Brooke-white** [comment]
Hey @jwaterworth,

I'm a bit confused, from git tag for v0.8.10, we are setting `supports_statement_cache=False` https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/blob/0.8.10/sqlalchemy_redshift/dialect.py#L563.

Could you confirm you're using the latest version of sqlalchemy_redshift? If you print something like `sqlalchemy_redshift.__version__` or `RedshiftDialect_redshift_connector.support_statement_cache` what do you see? I'd expect these to give `0.8.10` and `False` respectively.

> Before I found this issue I had a go at implementing the version of limit_clause mentioned [here](https://docs.sqlalchemy.org/en/14/core/connections.html#example-rendering-limit-offset-with-post-compile-parameters) which also seemed to fix the limit/offset caching issue and also didn't seem to require disabling statement caching. Any thoughts on this [PR](https://github.com/jwaterworth/sqlalchemy-redshift/pull/2/files) at all?

Thanks for taking the time to look into this more, I had started taking a look into this but time got away from me -- so I really appreciate you picking this up :)

A quick look over the PR  and it looks pretty much inline with the link provided to sqlalchemy docs, nice! One question I have though is why `support_statement_cache=False` on [L1131](https://github.com/jwaterworth/sqlalchemy-redshift/pull/2/files#diff-da4afac25892e729bdeca4533caf15820b269c54b5ad8bc7dbda7c47cdd76753R1131) I think you'd want this `True` as you've implemented all the mentioned logic for enabling :)

Of course we'd want to run this change through our CI + it'd be great if we could add some tests focused around limit/offset and caching to ensure we aren't breaking anything by doing this.

**Comment by farayal** [comment]
Hi  @Brooke-white

I have the same issue. I updated the package to v0.8.10 and the log message persist. I do this (Python 3.8.8):

`>>> import sqlalchemy_redshift`
`>>> print(sqlalchemy_redshift.__version__)`
`0.8.10`
`>>> from sqlalchemy_redshift.dialect import RedshiftDialect_redshift_connector`
`>>> print(RedshiftDialect_redshift_connector.supports_statement_cache)`
`True`

Line on [L1100](https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/blob/1c99efd02d6d135cf9e04d85df5b88444ff695dd/sqlalchemy_redshift/dialect.py#L1100) persist the flag `support_statement_cache=True`. Thanks for your work!

**Comment by Brooke-white** [comment]
@farayal @jwaterworth -- super strange, I am seeing this on my end. Let me investigate and will likely push another release shortly. apologies for the confusion folks!

**Comment by Brooke-white** [comment]
🤦‍♀️ A-hah I see...L1100 overrides L563 where I set this to False...will get a PR up shortly

**Comment by Brooke-white** [comment]
@farayal @jwaterworth I've made a new release v0.8.11 that fixes this, for real this time :)

```
Python 3.8.2 (v3.8.2:7b3ab5921f, Feb 24 2020, 17:52:18) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlalchemy_redshift
>>> print(sqlalchemy_redshift.__version__)
0.8.11
>>> from sqlalchemy_redshift.dialect import RedshiftDialect_redshift_connector
>>> print(RedshiftDialect_redshift_connector.supports_statement_cache)
False
>>> exit()
```

thanks for bearing with me through this, I appreciate your persistence!

**Comment by gmcrocetti** [comment]
Hey @Brooke-white . I'm still seeing this warning in a fresh install `SQLAlchemy==1.4.43` and `sqlalchemy-redshift==0.8.11`.
I've just submitted a patch in order to address it https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/pull/259.

**Comment by Brooke-white** [comment]
Hey @gmcrocetti , thank you for sharing & taking the time to submit a pr. my apologies that this is still surfacing.

**Comment by gmcrocetti** [comment]
> Hey @gmcrocetti , thank you for sharing & taking the time to submit a pr. my apologies that this is still surfacing.

No worries, the community exists to help :)

**Comment by Brooke-white** [comment]
@gmcrocetti thank you for your patience, we just release 0.8.12 which includes this fix :) please let me know if you folks still see this issue coming up, I'll keep this open until I get confirmation from you it's resolved

**Comment by gmcrocetti** [comment]
@Brooke-white . I'm not seeing it anymore. I'm glad it worked ! Thanks a lot
